<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Laba Rugi</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; line-height: 1.4; color: #333; }
        .container { padding: 20px; max-width: 800px; margin: 0 auto; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .header-left { flex: 1; }
        .header-right { flex: 1; text-align: right; }
        .store-name { font-size: 18px; font-weight: bold; margin-bottom: 5px; }
        .store-info { color: #666; margin-bottom: 3px; }
        .report-title { font-size: 20px; font-weight: bold; color: #333; margin-bottom: 10px; }
        .report-period { color: #666; }
        .summary-box { background: #f5f5f5; padding: 20px; margin: 30px 0; border-radius: 5px; border-left: 4px solid #007bff; }
        .summary-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #ddd; }
        .summary-row:last-child { border-bottom: none; }
        .summary-row.final { font-size: 16px; font-weight: bold; margin-top: 10px; padding-top: 15px; border-top: 2px solid #007bff; border-bottom: none; }
        .summary-label { font-size: 14px; }
        .summary-value { font-size: 14px; font-weight: bold; }
        .positive { color: #28a745; }
        .negative { color: #dc3545; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="header-left">
                <div class="store-name">{{ $storeSettings['name'] }}</div>
                @if($storeSettings['address'])
                    <div class="store-info">{{ $storeSettings['address'] }}</div>
                @endif
                @if($storeSettings['phone'])
                    <div class="store-info">Telp: {{ $storeSettings['phone'] }}</div>
                @endif
                @if($storeSettings['npwp'])
                    <div class="store-info">NPWP: {{ $storeSettings['npwp'] }}</div>
                @endif
            </div>
            <div class="header-right">
                <div class="report-title">LAPORAN LABA RUGI</div>
                <div class="report-period">
                    Periode: {{ date('d/m/Y', strtotime($data['from'])) }} - {{ date('d/m/Y', strtotime($data['to'])) }}
                </div>
                <div class="store-info" style="margin-top: 5px;">Dicetak: {{ date('d/m/Y H:i') }}</div>
            </div>
        </div>

        <div class="summary-box">
            <div class="summary-row">
                <span class="summary-label">Total Penjualan</span>
                <span class="summary-value positive">Rp {{ number_format($data['totalSales'], 0, ',', '.') }}</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Total Pembelian</span>
                <span class="summary-value negative">Rp {{ number_format($data['totalPurchases'], 0, ',', '.') }}</span>
            </div>
            <div class="summary-row final">
                <span class="summary-label">Laba Kotor</span>
                <span class="summary-value {{ $data['grossProfit'] >= 0 ? 'positive' : 'negative' }}">
                    Rp {{ number_format($data['grossProfit'], 0, ',', '.') }}
                </span>
            </div>
        </div>

        <div style="text-align: center; margin-top: 30px; color: #666; font-size: 11px;">
            <p style="margin-bottom: 5px;">Laporan ini mencakup semua transaksi penjualan dan pembelian pada periode yang dipilih.</p>
            <p>Laba kotor = Total Penjualan - Total Pembelian</p>
        </div>

        <div class="footer">
            <div>Generated by TokoSync ERP</div>
            <div>{{ $storeSettings['name'] }} - {{ date('d/m/Y H:i') }}</div>
        </div>
    </div>
</body>
</html>
