<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Stok</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; line-height: 1.4; color: #333; }
        .container { padding: 15px 20px; }
        .header { display: flex; justify-content: space-between; margin-bottom: 25px; }
        .header-left { flex: 1; }
        .header-right { flex: 1; text-align: right; }
        .store-name { font-size: 16px; font-weight: bold; margin-bottom: 5px; }
        .store-info { color: #666; margin-bottom: 3px; }
        .report-title { font-size: 20px; font-weight: bold; color: #333; margin-bottom: 10px; }
        .report-date { color: #666; }
        .summary { background: #f5f5f5; padding: 15px; margin: 20px 0; border-radius: 5px; display: flex; justify-content: space-between; align-items: center; }
        .summary-label { font-size: 14px; color: #666; }
        .summary-value { font-size: 24px; font-weight: bold; color: #28a745; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f9f9f9; font-weight: bold; }
        .text-right { text-align: right; }
        .low-stock { background: #fff3cd; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="header-left">
                <div class="store-name">{{ $storeSettings['name'] }}</div>
                @if($storeSettings['address'])
                    <div class="store-info">{{ $storeSettings['address'] }}</div>
                @endif
                @if($storeSettings['phone'])
                    <div class="store-info">Telp: {{ $storeSettings['phone'] }}</div>
                @endif
            </div>
            <div class="header-right">
                <div class="report-title">LAPORAN STOK</div>
                <div class="report-date">Dicetak: {{ date('d/m/Y H:i') }}</div>
            </div>
        </div>

        <div class="summary">
            <div class="summary-label">Total Nilai Stok</div>
            <div class="summary-value">Rp {{ number_format($data['totalValue'], 0, ',', '.') }}</div>
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">No</th>
                    <th style="width: 12%;">Kode</th>
                    <th style="width: 25%;">Nama Produk</th>
                    <th style="width: 10%;">Kategori</th>
                    <th style="width: 8%;">Stok</th>
                    <th style="width: 8%;">Satuan</th>
                    <th style="width: 15%;" class="text-right">Harga Beli</th>
                    <th style="width: 15%;" class="text-right">Nilai Stok</th>
                </tr>
            </thead>
            <tbody>
                @php($no = 1)
                @foreach($data['items'] as $item)
                    <tr class="{{ $item['stock'] <= 0 ? 'low-stock' : '' }}">
                        <td>{{ $no++ }}</td>
                        <td>{{ $item['code'] }}</td>
                        <td>{{ $item['name'] }}</td>
                        <td>{{ $item['category'] ?? '-' }}</td>
                        <td class="{{ $item['stock'] <= 0 ? 'text-red-600 font-bold' : '' }}">{{ $item['stock'] }}</td>
                        <td>{{ $item['unit'] }}</td>
                        <td class="text-right">Rp {{ number_format($item['buyPrice'], 0, ',', '.') }}</td>
                        <td class="text-right">Rp {{ number_format($item['stockValue'], 0, ',', '.') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <div>Generated by TokoSync ERP</div>
            <div>{{ $storeSettings['name'] }} - {{ date('d/m/Y H:i') }}</div>
        </div>
    </div>
</body>
</html>
